// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
<script src="js/transition.js" defer></script>
<script src="js/alert.js" defer></script>
<script src="js/button.js" defer></script>
<script src="js/carousel.js" defer></script>
<script src="js/collapse.js" defer></script>
<script src="js/dropdown.js" defer></script>
<script src="js/modal.js" defer></script>
<script src="js/tooltip.js" defer></script>
<script src="js/popover.js" defer></script>
<script src="js/scrollspy.js" defer></script>
<script src="js/tab.js" defer></script>
<script src="js/affix.js" defer></script>